name: rikulo_gap
version: 0.5.1+3
description: >
  Rikulo Gap is a bridge implementation of Apache Cordova/PhoneGap which enables
  developers to access native resources of mobile platforms using the HTML5 and Dart.
authors:
- Henri Chen <henrichen@rikulo.org>
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org
dependencies:
  js: any
  rikulo_commons: any
  rikulo_ui: any
