name: rikulo_gap
version: 0.6.0
description: Rikulo Gap is a bridge implementation of Apache Cordova enabling developers to access native resources of mobile platforms using the HTML5 and Dart.
authors:
- Abby Yeh <b01902102@ntu.edu.tw>
- Urchin Wang <b01902080@ntu.edu.tw>
- Henri Chen <henrichen@rikulo.org>
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org
dependencies:
dev_dependencies:
  unittest: any
  browser: any
environment:
  sdk: ">=1.4.0"
